version: '3.8'

services:
  decibelio-db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_DB: decibeliodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@987
    ports:
      - ${DB_PORT_PUBLIC}:5432
    volumes:
      - decibelio-db-data:/var/lib/postgresql/data
    networks:
      - decibelio-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      replicas: 2 # Aumentar a 2 réplicas

  decibelio-api:
    build:
      context: ../decibelio
      dockerfile: Dockerfile
    image: decibelio-api:latest
    restart: unless-stopped
    environment:
      - DRIVER_JDBC_DIR=/config/
      - DB_SERVER_NAME=decibelio-db
      - DB_PORT_NUMBER=5432
      - DB_NAME=decibeliodb
      - DB_USER=postgres
      - DB_PASSWORD=admin@987
    ports:
      - "9080:9080"
      - "9443:9443"
    depends_on:
      - decibelio-db
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
      replicas: 2
    networks:
      - decibelio-network

  decibelio-webapp:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - decibelio-web-bind:/usr/share/nginx/html:ro
      - ../decibelio_app_web/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - decibelio-api
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
      replicas: 2
    networks:
      - decibelio-network

networks:
  decibelio-network:
    driver: bridge

volumes:
  decibelio-db-data:
    name: decibelio-db-data
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_DATA_DIR_BD}
      o: bind
  decibelio-web-bind:
    name: decibelio-web-bind
    driver: local
    driver_opts:
      type: none
      device: ../decibelio_app_web/build/web
      o: bind
  decibelio-web-nginx_config:
    driver: local
    driver_opts:
      type: none
      device: ../decibelio_app_web/nginx.conf
      o: bind
