name: build Jakarta-Decibelio-Karencita

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Checkout del repositorio
      - uses: actions/checkout@v4

      # Configurar JDK 17
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Construir con Maven
        run: |
          cd decibelio
          chmod +x mvnw
          ./mvnw clean package

      - name: Verificar contenido del directorio target
        run: |
          cd decibelio
          ls -la target

      - name: Copiar binarios
        run: |
          cd decibelio
          mkdir -p candidate-binary
          cp target/*.war candidate-binary/

      # Ejecutar pruebas con Maven
      - name: Ejecutar pruebas con Maven
        run: |
          cd decibelio
          ./mvnw test

      - name: Copiar resultados de pruebas
        run: |
            cd decibelio
            mkdir -p test-results
            find target -name 'TEST-*.xml' -exec cp {} test-results/ \;
  
      # Subir binarios de la aplicaci贸n
      - name: Subir binarios de la aplicaci贸n
        uses: actions/upload-artifact@v3
        with:
          name: Application-Binary
          path: decibelio/candidate-binary

      # Subir resultados de pruebas
      - name: Subir resultados de pruebas
        uses: actions/upload-artifact@v3
        with:
          name: Test-Results
          path: decibelio/test-results

      # Publicar resultados de pruebas
      - name: Publicar Resultados de Pruebas
        uses: EnricoMi/publish-unit-test-result-action@v2.0.0
        if: always()
        with:
          junit_files: "decibelio/test-results/**/*.xml"

      # Configurar Flutter
      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      # Instalar dependencias de Flutter
      - name: Instalar dependencias de Flutter
        run: |
          cd decibelio_app_web
          flutter pub get

      # Construir aplicaci贸n Flutter para la web
      - name: Construir aplicaci贸n Flutter (Web)
        run: |
          cd decibelio_app_web
          flutter build web

      # # Ejecutar pruebas de Flutter
      # # - name: Ejecutar pruebas con Flutter
      # #   run: |
      # #     cd decibelio_app_web
      #     flutter test

      # # Copiar resultados de las pruebas de Flutter
      # - name: Copiar resultados de pruebas de Flutter
      #   run: |
      #     cd decibelio_app_web
      #     mkdir -p test-results
      #     find test -name 'test_*.dart' -exec cp {} decibelio_app_web/test-results/ \;

      # # Subir resultados de pruebas de Flutter
      # - name: Subir resultados de pruebas de Flutter
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Flutter-Test-Results
      #     path: decibelio_app_web/test-results

      # # Publicar resultados de pruebas de Flutter
      # - name: Publicar Resultados de Pruebas de Flutter
      #   uses: EnricoMi/publish-unit-test-result-action@v2.0.0
      #   if: always()
      #   with:
      #     junit_files: "decibelio_app_web/test-results/**/*.xml"