name: build Jakarta-Decibelio-Karencita

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Checkout del repositorio
      - uses: actions/checkout@v4

      # Configurar JDK 17
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Construir con Maven desde la carpeta 'decibelio'
      - name: Construir con Maven
        run: |
          cd decibelio
          chmod +x mvnw
          ./mvnw clean package

      # Copiar binarios
      - name: Copiar binarios
        run: |
          cd decibelio
          mkdir -p candidate-binary
          cp target/*.jar candidate-binary/

      # Ejecutar pruebas con Maven
      - name: Ejecutar pruebas con Maven
        run: |
          cd decibelio
          ./mvnw test

      # Copiar resultados de pruebas
      - name: Copiar resultados de pruebas
        run: |
          cd decibelio
          mkdir -p test-results
          cp target/*-reports/TEST-*.xml test-results/

      # Subir binarios de la aplicación
      - name: Subir binarios de la aplicación
        uses: actions/upload-artifact@v3
        with:
          name: Application-Binary
          path: decibelio/candidate-binary

      # Subir resultados de pruebas
      - name: Subir resultados de pruebas
        uses: actions/upload-artifact@v3
        with:
          name: Test-Results
          path: decibelio/test-results

      # Publicar resultados de pruebas
      - name: Publicar Resultados de Pruebas
        uses: EnricoMi/publish-unit-test-result-action@v2.0.0
        if: always()
        with:
          junit_files: "decibelio/test-results/**/*.xml"