name: build Jakarta-Decibelio-Karencita

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Construir y probar aplicación Java
        run: |
          cd decibelio
          chmod +x mvnw
          ./mvnw clean package test
          mkdir -p test-results
          find target -name 'TEST-*.xml' -exec cp {} test-results/ \;
        env:
          MAVEN_OPTS: "-Xmx1024m"

      - name: Verificar resultados de pruebas Maven
        run: |
          cd decibelio/test-results
          ls -l || echo "No se encontraron resultados de pruebas Maven."

      - name: Publicar resultados de pruebas Maven
        uses: EnricoMi/publish-unit-test-result-action@v2.4.0
        if: always()
        with:
          junit_files: "decibelio/test-results/**/*.xml"

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Instalar y construir aplicación Flutter (Web)
        run: |
          cd decibelio_app_web
          flutter pub get
          flutter build web
          mkdir -p test-results
          find build -name 'test-*.xml' -exec cp {} test-results/ \;

      - name: Verificar resultados de pruebas Flutter
        run: |
          cd decibelio_app_web/test-results
          ls -l || echo "No se encontraron resultados de pruebas Flutter."

      - name: Publicar resultados de pruebas Flutter
        uses: EnricoMi/publish-unit-test-result-action@v2.4.0
        if: always()
        with:
          junit_files: "decibelio_app_web/test-results/**/*.xml"

      - name: Subir artefactos
        uses: actions/upload-artifact@v3
        with:
          name: Application-Artifacts
          path: |
            decibelio/target/*.war
            decibelio/test-results
            decibelio_app_web/test-results