name:  02 Build pipeline

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Checkout del repositorio
      - uses: actions/checkout@v4

      # Configurar JDK 17
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Construir y ejecutar pruebas con Maven
      - name: Construir y ejecutar pruebas con Maven
        run: |
          cd decibelio
          chmod +x mvnw
          ./mvnw clean package test
        env:
          MAVEN_OPTS: "-Xmx1024m"

      # Copiar resultados de pruebas de Maven
      - name: Copiar resultados de pruebas de Maven
        run: |
          cd decibelio
          mkdir -p test-results
          find target -name 'TEST-*.xml' -exec cp {} test-results/ \;
          ls -la test-results  # Verificar los archivos copiados

      # Publicar resultados de pruebas de Maven
      - name: Publicar Resultados de Pruebas de Maven
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "decibelio/test-results/**/*.xml"

      # Configurar Flutter
      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      # Instalar dependencias de Flutter
      - name: Instalar dependencias de Flutter
        run: |
          cd decibelio_app_web
          flutter pub get

      # Construir aplicaci贸n Flutter para la web
      - name: Construir aplicaci贸n Flutter (Web)
        run: |
          cd decibelio_app_web
          flutter build web

      # Copiar resultados de pruebas de Flutter
      - name: Copiar resultados de pruebas de Flutter
        run: |
          cd decibelio_app_web
          mkdir -p test-results
          find build -name 'test-*.xml' -exec cp {} test-results/ \;
          ls -la test-results  # Verificar los archivos copiados

      # Publicar resultados de pruebas de Flutter
      - name: Publicar Resultados de Pruebas de Flutter
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "decibelio_app_web/test-results/**/*.xml"

      # Subir binarios de la aplicaci贸n
      - name: Subir binarios de la aplicaci贸n
        uses: actions/upload-artifact@v3
        with:
          name: Application-Binary
          path: decibelio/target/*.war

      # Subir resultados de pruebas de Maven
      - name: Subir resultados de pruebas de Maven
        uses: actions/upload-artifact@v3
        with:
          name: Maven-Test-Results
          path: decibelio/test-results

      # Subir resultados de pruebas de Flutter
      - name: Subir resultados de pruebas de Flutter
        uses: actions/upload-artifact@v3
        with:
          name: Flutter-Test-Results
          path: decibelio_app_web/test-results