name: Deploy to Server

on: 
  workflow_call:  # Este bloque permite que otro workflow lo llame

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar aplicación en el servidor
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 192.168.50.161
          username: kareg
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd DECIBELIO
            git pull origin main  # Obtener los últimos cambios del código
            cd decibelio
            ./mvnw clean package
            sudo docker compose --env-file .env -f docker-compose.yml up --build -d
            echo "🚀 Despliegue completado con éxito"