name: 06 Build Docker Image with Docker Compose

on:
    workflow_dispatch:
    workflow_call:
        outputs:
            image-tag:
                description: "The tag of my image test"
                value: ${{ jobs.docker.outputs.image-tag }}

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    docker:
        outputs:
            image-tag: ${{ steps.meta.outputs.tags }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        
        steps:
        - uses: actions/checkout@v3
        - name: Download application binary
          uses: actions/download-artifact@v3.0.0
          with:
            name: Application-Binary
            path: target
        - name: Log in to the Container registry
          uses: docker/login-action@v2.1.0
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v4.1.0
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            tags: |
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
              type=ref,event=pr
              type=ref,event=tag
              type=ref,event=branch
              type=schedule,pattern=main
        - name: Build Decibelio with Maven
          run: |
            cd decibelio
            ./mvnw clean package
        - name: Start services in decibelio with Docker Compose
          env:
            POSTGRES_VERSION: ${{ secrets.POSTGRES_VERSION }}
            DB_PORT_PUBLIC: ${{ secrets.DB_PORT_PUBLIC }}
            LOCAL_DATA_DIR_BD: ${{ secrets.LOCAL_DATA_DIR_BD }}
          run: |
            cd decibelio
            docker-compose -f docker-compose.yml up -d
        - name: Deploy Decibelio in production
          run: |
            cd decibelio-deploy
            sudo docker-compose --env-file .env -f docker-compose.yml up --build -d