name: Build and Deploy Decibelio

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cambia al directorio "decibelio" y construye la aplicación con Maven
      - name: Build Decibelio with Maven
        run: |
          cd decibelio
          ./mvnw clean package

      # Levanta servicios en la carpeta "decibelio" usando docker-compose
      - name: Start services in decibelio
        env:
          POSTGRES_VERSION: ${{ secrets.POSTGRES_VERSION }}
          DB_PORT_PUBLIC: ${{ secrets.DB_PORT_PUBLIC }}
          LOCAL_DATA_DIR_BD: ${{ secrets.LOCAL_DATA_DIR_BD }}
        run: |
          cd decibelio
          docker-compose -f docker-compose.yml up -d

      # Cambia a la carpeta "decibelio-deploy" y construye/despliega
      - name: Deploy Decibelio in production
        run: |
          cd decibelio-deploy
          sudo docker-compose --env-file .env -f docker-compose.yml up --build -d