name: 05 License Compliance

on:
  workflow_dispatch:
  workflow_call:

jobs:
  license-finder:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [java] # Solo Java ahora

    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuración para Java
      - name: Run License Finder for Java
        if: ${{ matrix.language == 'java' }}
        uses: jmservera/license-finder-action@main
        with:
          permitted-licenses: |
            MIT, Apache-2.0
          approved-dependencies: |
            junit, junit-jupiter
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_17_x64

      # Publicar resultados
      - name: Publish License Check Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2.2.0
        with:
          junit_files: "license_finder_report.xml"
          check_name: "License Compliance Check"

      - name: Upload Dependency Review Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: license-finder-report
          path: ${{ github.workspace }}/license_finder_report.xml
