name: 05 License Compliance

on:
  workflow_dispatch:
  workflow_call:

jobs:
  license-finder:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [java, flutter]

    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuraci칩n para Java
      - name: Run License Finder for Java
        if: ${{ matrix.language == 'java' }}
        uses: jmservera/license-finder-action@main
        with:
          permitted-licenses: |
            MIT, Apache-2.0
          approved-dependencies: |
            junit, junit-jupiter
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_17_x64

      # Configuraci칩n para Flutter
      - name: Setup Flutter
        if: ${{ matrix.language == 'flutter' }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # Especifica la versi칩n exacta que est치s usando
          channel: 'stable'

      - name: Install Flutter Dependencies
        working-directory: decibelio_app_web
        if: ${{ matrix.language == 'flutter' }}
        run: flutter pub get

      - name: Run Flutter License Check
        working-directory: decibelio_app_web
        if: ${{ matrix.language == 'flutter' }}
        run: flutter pub run license_checker
        
      # Publicar resultados
      - name: Publish License Check Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2.2.0
        with:
          junit_files: "license_finder_report.xml"
          check_name: "License Compliance Check"

      - name: Upload Dependency Review Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: license-finder-report
          path: ${{ github.workspace }}/license_finder_report.xml